"""Job listing data source for JobSwiper.

Every caller downstream (the /api/jobs route, the draft-generation
prompt, the swiper UI) only ever consumes the plain dict shape returned
by get_jobs()/get_job_by_id() below -- never anything mock-specific.
That's deliberate: swapping this file's two functions for real calls
to the Careerjet affiliate API (https://www.careerjet.com/partners/api/)
is the only change needed to go live with real listings. Careerjet's
search endpoint returns fields that map directly onto this shape
(title, company/salary as free text, url, locations) -- the "email"
field has no Careerjet equivalent and would stay "" for every real
listing until/unless a future source provides one, which the swiper's
existing "no email listed" path already handles.
"""

MOCK_JOBS = [
    {
        "id": "sa-001",
        "title": "Junior Sales Associate",
        "company": "Mr Price",
        "location": "Cape Town, Western Cape",
        "salary": "R6,500 - R8,000 / month",
        "description": "Help customers find what they need on the floor, work the till, and keep the store looking sharp. No experience required -- full training given. Retail hours, including some weekends.",
        "posted_at": "2026-07-14",
        "email": "recruitment@mrpricecapetown.example",
        "url": "https://www.careerjet.co.za/jobad/example-mr-price-sales-associate",
    },
    {
        "id": "sa-002",
        "title": "Junior Frontend Developer",
        "company": "Yoco",
        "location": "Cape Town, Western Cape (Hybrid)",
        "salary": "R25,000 - R35,000 / month",
        "description": "Join our product team building the dashboard South African small businesses use every day. React, TypeScript. We care more about how you think than your CV -- a strong portfolio or GitHub matters more than a degree.",
        "posted_at": "2026-07-15",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-yoco-frontend-dev",
    },
    {
        "id": "sa-003",
        "title": "Call Centre Agent",
        "company": "Discovery",
        "location": "Sandton, Gauteng",
        "salary": "R7,200 / month + incentives",
        "description": "Handle inbound client queries for our health plans. Matric required, clear credit and criminal record. Full product training provided in your first two weeks.",
        "posted_at": "2026-07-12",
        "email": "callcentre.jobs@discovery.example",
        "url": "https://www.careerjet.co.za/jobad/example-discovery-call-centre",
    },
    {
        "id": "sa-004",
        "title": "Warehouse Assistant",
        "company": "Takealot",
        "location": "Johannesburg, Gauteng",
        "salary": "R6,800 / month",
        "description": "Pick, pack, and dispatch customer orders in a fast-paced fulfilment centre. Shift work, on your feet most of the day. Physically fit, reliable, punctual.",
        "posted_at": "2026-07-10",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-takealot-warehouse",
    },
    {
        "id": "sa-005",
        "title": "Junior Bookkeeper",
        "company": "Sage",
        "location": "Durban, KwaZulu-Natal (Remote)",
        "salary": "R12,000 - R16,000 / month",
        "description": "Support our accounts team with invoicing, reconciliations, and data capture on Sage Accounting. Studying towards or holding a bookkeeping/accounting qualification preferred, not required.",
        "posted_at": "2026-07-16",
        "email": "earlycareers@sage.example",
        "url": "https://www.careerjet.co.za/jobad/example-sage-junior-bookkeeper",
    },
    {
        "id": "sa-006",
        "title": "Waitron",
        "company": "Vida e Caffè",
        "location": "Pretoria, Gauteng",
        "salary": "R4,500 / month + tips",
        "description": "Front-of-house at one of our busiest branches -- taking orders, serving customers, keeping the till honest. Friendly, energetic, available weekends.",
        "posted_at": "2026-07-11",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-vida-waitron",
    },
    {
        "id": "sa-007",
        "title": "IT Support Intern",
        "company": "Standard Bank",
        "location": "Johannesburg, Gauteng",
        "salary": "R9,500 / month (12-month internship)",
        "description": "First-line desktop and network support for internal staff under our graduate internship programme. IT diploma or degree (completed or final year) required.",
        "posted_at": "2026-07-13",
        "email": "graduateprogramme@standardbank.example",
        "url": "https://www.careerjet.co.za/jobad/example-standard-bank-it-intern",
    },
    {
        "id": "sa-008",
        "title": "Social Media Coordinator",
        "company": "Woolworths",
        "location": "Cape Town, Western Cape",
        "salary": "R14,000 - R18,000 / month",
        "description": "Plan and post daily content across Instagram, TikTok, and X for our food and lifestyle brand. A portfolio of your own content (personal or freelance) counts more than formal experience.",
        "posted_at": "2026-07-09",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-woolworths-social-media",
    },
    {
        "id": "sa-009",
        "title": "Junior Electrician",
        "company": "Eskom",
        "location": "Polokwane, Limpopo",
        "salary": "R11,000 - R14,000 / month",
        "description": "Assist qualified electricians on maintenance and installation work across our regional grid. Trade test or relevant N-qualification required. Own transport to site an advantage.",
        "posted_at": "2026-07-08",
        "email": "artisan.recruitment@eskom.example",
        "url": "https://www.careerjet.co.za/jobad/example-eskom-junior-electrician",
    },
    {
        "id": "sa-010",
        "title": "Data Capturer",
        "company": "Old Mutual",
        "location": "Cape Town, Western Cape (Remote)",
        "salary": "R6,000 / month",
        "description": "Accurately capture policy and claims data into our internal systems. Fast, accurate typing, comfortable with repetitive detail-focused work, own laptop and stable internet.",
        "posted_at": "2026-07-15",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-old-mutual-data-capturer",
    },
    {
        "id": "sa-011",
        "title": "Junior Graphic Designer",
        "company": "Takealot",
        "location": "Cape Town, Western Cape (Hybrid)",
        "salary": "R16,000 - R22,000 / month",
        "description": "Design banners, product imagery, and campaign creative for our marketing team. Figma and Adobe Suite. Send us a portfolio link -- that's what we actually look at first.",
        "posted_at": "2026-07-16",
        "email": "creative.careers@takealot.example",
        "url": "https://www.careerjet.co.za/jobad/example-takealot-junior-designer",
    },
    {
        "id": "sa-012",
        "title": "Security Officer",
        "company": "Fidelity Services Group",
        "location": "Durban, KwaZulu-Natal",
        "salary": "R6,200 / month",
        "description": "Access control and patrol duties at a corporate site. Valid PSIRA grade C or higher, clear criminal record, own transport to shifts.",
        "posted_at": "2026-07-07",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-fidelity-security-officer",
    },
    {
        "id": "sa-013",
        "title": "Cashier",
        "company": "Pick n Pay",
        "location": "Bellville, Western Cape",
        "salary": "R5,800 / month",
        "description": "Front-till operations, customer service, and basic stock replenishment during quiet periods. Matric preferred but not required. Full point-of-sale training given in-store.",
        "posted_at": "2026-07-16",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-pnp-cashier",
    },
    {
        "id": "sa-014",
        "title": "Pharmacy Assistant (Learnership)",
        "company": "Clicks",
        "location": "Pretoria, Gauteng",
        "salary": "R5,500 / month (12-month learnership, NQF 4 qualification on completion)",
        "description": "Learn the ropes of front-shop and dispensary support under a registered pharmacist while working toward your Pharmacist's Assistant qualification. Matric with Maths and Science preferred.",
        "posted_at": "2026-07-13",
        "email": "learnerships@clicks.example",
        "url": "https://www.careerjet.co.za/jobad/example-clicks-pharmacy-learnership",
    },
    {
        "id": "sa-015",
        "title": "Junior Software Tester (QA)",
        "company": "Capitec Bank",
        "location": "Stellenbosch, Western Cape (Hybrid)",
        "salary": "R22,000 - R28,000 / month",
        "description": "Manual and early automated testing on our banking app before release. IT-related diploma/degree or equivalent self-taught experience -- a GitHub with real test scripts counts for a lot here.",
        "posted_at": "2026-07-14",
        "email": "graduates@capitecbank.example",
        "url": "https://www.careerjet.co.za/jobad/example-capitec-junior-qa",
    },
    {
        "id": "sa-016",
        "title": "Bank Teller",
        "company": "FNB",
        "location": "Soweto, Gauteng",
        "salary": "R9,000 - R11,000 / month",
        "description": "Front-line cash handling and account queries at a busy branch. Matric required, clear ITC/credit record, comfortable working with money and targets.",
        "posted_at": "2026-07-11",
        "email": "branchcareers@fnb.example",
        "url": "https://www.careerjet.co.za/jobad/example-fnb-bank-teller",
    },
    {
        "id": "sa-017",
        "title": "Customer Service Agent",
        "company": "Vodacom",
        "location": "Midrand, Gauteng",
        "salary": "R8,500 / month + commission",
        "description": "Handle inbound queries on billing, upgrades, and network issues for a major mobile network. Clear telephone manner, basic computer literacy, matric.",
        "posted_at": "2026-07-15",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-vodacom-customer-service",
    },
    {
        "id": "sa-018",
        "title": "Delivery Driver (Code 08)",
        "company": "Checkers Sixty60",
        "location": "Port Elizabeth, Eastern Cape",
        "salary": "R6,500 / month + fuel allowance",
        "description": "Same-day grocery delivery on our own scooter/bakkie fleet. Valid Code 08 licence, clean driving record, own smartphone for the delivery app.",
        "posted_at": "2026-07-12",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-sixty60-delivery-driver",
    },
    {
        "id": "sa-019",
        "title": "General Worker",
        "company": "Tiger Brands",
        "location": "Germiston, Gauteng",
        "salary": "R6,300 / month",
        "description": "Production-line support at a food manufacturing plant -- packing, quality checks, keeping the line moving. Physically fit, able to work rotating shifts including nights.",
        "posted_at": "2026-07-09",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-tigerbrands-general-worker",
    },
    {
        "id": "sa-020",
        "title": "Junior Marketing Assistant",
        "company": "Nando's",
        "location": "Randburg, Gauteng",
        "salary": "R13,000 - R16,000 / month",
        "description": "Support local store marketing campaigns, social content, and in-store promo rollout. A marketing diploma helps but a genuinely strong personal social media presence matters just as much.",
        "posted_at": "2026-07-16",
        "email": "marketing.careers@nandos.example",
        "url": "https://www.careerjet.co.za/jobad/example-nandos-junior-marketing",
    },
    {
        "id": "sa-021",
        "title": "Admin Clerk",
        "company": "City of Johannesburg (Metro)",
        "location": "Johannesburg, Gauteng",
        "salary": "R8,200 / month",
        "description": "General administrative support to a regional municipal office -- filing, data capture, front-desk queries. Matric required, South African citizen, no criminal record.",
        "posted_at": "2026-07-08",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-joburg-metro-admin-clerk",
    },
    {
        "id": "sa-022",
        "title": "Junior Data Analyst",
        "company": "Sanlam",
        "location": "Bellville, Western Cape (Hybrid)",
        "salary": "R20,000 - R26,000 / month",
        "description": "Support the actuarial and insights team with reporting and basic Python/SQL analysis on policy data. A stats/actuarial-related qualification or a strong personal data project both count as real evidence here.",
        "posted_at": "2026-07-15",
        "email": "graduate.programme@sanlam.example",
        "url": "https://www.careerjet.co.za/jobad/example-sanlam-junior-data-analyst",
    },
    {
        "id": "sa-023",
        "title": "Hotel Front Desk Agent",
        "company": "City Lodge Hotels",
        "location": "Sandton, Gauteng",
        "salary": "R8,000 / month + tips",
        "description": "Check-in/check-out, guest queries, and basic reservations on our front-of-house system. Matric, well presented, comfortable on your feet for a full shift, weekend availability.",
        "posted_at": "2026-07-10",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-citylodge-front-desk",
    },
    {
        "id": "sa-024",
        "title": "Junior Bricklayer / Trade Assistant",
        "company": "Group Five Construction",
        "location": "Bloemfontein, Free State",
        "salary": "R7,500 - R9,500 / month",
        "description": "On-site support to qualified bricklayers on a residential development. Trade test or relevant experience preferred, willing to train a strong, reliable general labourer.",
        "posted_at": "2026-07-07",
        "email": "sitejobs@groupfive.example",
        "url": "https://www.careerjet.co.za/jobad/example-groupfive-trade-assistant",
    },
    {
        "id": "sa-025",
        "title": "Junior Underwriter",
        "company": "Old Mutual",
        "location": "Pinetown, KwaZulu-Natal",
        "salary": "R15,000 - R19,000 / month",
        "description": "Assess and process personal lines insurance applications under supervision. A business/finance-related qualification helps, but strong attention to detail and clear written communication matter more.",
        "posted_at": "2026-07-14",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-oldmutual-junior-underwriter",
    },
    {
        "id": "sa-026",
        "title": "Care Worker (Home-Based Care)",
        "company": "Life Healthcare",
        "location": "East London, Eastern Cape",
        "salary": "R7,000 / month",
        "description": "Provide basic home-based patient care under nursing supervision -- hygiene support, vitals monitoring, companionship. A caregiving certificate is a plus, genuine compassion and reliability are non-negotiable.",
        "posted_at": "2026-07-13",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-lifehealthcare-care-worker",
    },
    {
        "id": "sa-027",
        "title": "Teaching Assistant (Foundation Phase)",
        "company": "Curro Schools",
        "location": "Centurion, Gauteng",
        "salary": "R9,000 / month",
        "description": "Support a Grade 1-3 classroom teacher with lesson prep, marking, and small-group reading support. Studying towards or holding an education-related qualification preferred.",
        "posted_at": "2026-07-16",
        "email": "recruitment@curro.example",
        "url": "https://www.careerjet.co.za/jobad/example-curro-teaching-assistant",
    },
    {
        "id": "sa-028",
        "title": "Junior DevOps / Cloud Support",
        "company": "MTN",
        "location": "Roodepoort, Gauteng (Hybrid)",
        "salary": "R28,000 - R38,000 / month",
        "description": "Support our cloud infrastructure team with monitoring, basic scripting, and incident triage. AWS/Azure fundamentals certification or a real home-lab project matters more than a formal degree here.",
        "posted_at": "2026-07-15",
        "email": "tech.careers@mtn.example",
        "url": "https://www.careerjet.co.za/jobad/example-mtn-junior-devops",
    },
    {
        "id": "sa-029",
        "title": "Forklift Operator",
        "company": "Bidvest Logistics",
        "location": "Durban, KwaZulu-Natal",
        "salary": "R9,200 / month",
        "description": "Load/unload and internal stock movement at a busy distribution centre. Valid forklift licence required, shift work including weekends.",
        "posted_at": "2026-07-11",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-bidvest-forklift-operator",
    },
    {
        "id": "sa-030",
        "title": "Junior Copywriter",
        "company": "Ogilvy South Africa",
        "location": "Rosebank, Gauteng (Hybrid)",
        "salary": "R14,000 - R18,000 / month",
        "description": "Write ad copy, social captions, and campaign concepts across a mix of local brands. Send a portfolio of your own writing (student work, personal blog, freelance -- anything real) instead of just a CV.",
        "posted_at": "2026-07-16",
        "email": "junior.creatives@ogilvy.example",
        "url": "https://www.careerjet.co.za/jobad/example-ogilvy-junior-copywriter",
    },
    {
        "id": "sa-031",
        "title": "Petrol Attendant",
        "company": "Engen",
        "location": "Nelspruit, Mpumalanga",
        "salary": "R5,200 / month + tips",
        "description": "Fuel service, basic vehicle checks, and till operations at a busy filling station. Matric preferred, must be comfortable on your feet outdoors for full shifts.",
        "posted_at": "2026-07-09",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-engen-petrol-attendant",
    },
    {
        "id": "sa-032",
        "title": "HR Intern",
        "company": "Discovery",
        "location": "Sandton, Gauteng",
        "salary": "R8,800 / month (12-month internship)",
        "description": "Support recruitment coordination, onboarding admin, and basic HR record-keeping. HR-related diploma/degree (completed or final year) required.",
        "posted_at": "2026-07-14",
        "email": "hr.internships@discovery.example",
        "url": "https://www.careerjet.co.za/jobad/example-discovery-hr-intern",
    },
    {
        "id": "sa-033",
        "title": "Junior Mechanic",
        "company": "Toyota South Africa",
        "location": "Boksburg, Gauteng",
        "salary": "R9,800 - R12,500 / month",
        "description": "Service and basic repair work under a qualified technician at a dealership workshop. Trade test in motor mechanics or a relevant apprenticeship required.",
        "posted_at": "2026-07-08",
        "email": "workshop.careers@toyota.example",
        "url": "https://www.careerjet.co.za/jobad/example-toyota-junior-mechanic",
    },
    {
        "id": "sa-034",
        "title": "Reservations Consultant",
        "company": "Tsogo Sun Hotels",
        "location": "Umhlanga, KwaZulu-Natal",
        "salary": "R9,500 / month",
        "description": "Handle phone and email booking enquiries across our hotel group. Clear spoken and written English, additional local languages a strong plus, basic computer literacy.",
        "posted_at": "2026-07-12",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-tsogosun-reservations",
    },
    {
        "id": "sa-035",
        "title": "Junior Quantity Surveyor",
        "company": "WBHO Construction",
        "location": "Cape Town, Western Cape",
        "salary": "R18,000 - R24,000 / month",
        "description": "Support cost estimation and site measurement on commercial builds under a senior QS. Relevant diploma/degree (completed or final year) required.",
        "posted_at": "2026-07-15",
        "email": "graduates@wbho.example",
        "url": "https://www.careerjet.co.za/jobad/example-wbho-junior-qs",
    },
    {
        "id": "sa-036",
        "title": "Beauty Therapist",
        "company": "Sorbet",
        "location": "Fourways, Gauteng",
        "salary": "R7,500 / month + commission",
        "description": "Nails, waxing, and basic facials at a busy salon branch. Relevant beauty therapy qualification required, friendly and reliable with weekend availability.",
        "posted_at": "2026-07-13",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-sorbet-beauty-therapist",
    },
    {
        "id": "sa-037",
        "title": "Junior Environmental Officer",
        "company": "Sibanye-Stillwater",
        "location": "Rustenburg, North West",
        "salary": "R17,000 - R21,000 / month",
        "description": "Support environmental compliance monitoring and reporting at a mining operation. Environmental science-related diploma/degree required, own transport to site.",
        "posted_at": "2026-07-10",
        "email": "graduate.intake@sibanyestillwater.example",
        "url": "https://www.careerjet.co.za/jobad/example-sibanye-junior-environmental",
    },
    {
        "id": "sa-038",
        "title": "Contact Centre Agent",
        "company": "Teleperformance",
        "location": "Cape Town, Western Cape",
        "salary": "R7,800 / month + incentives",
        "description": "Inbound customer support for an international client account. Clear spoken English, matric, no experience necessary -- full paid training provided before you take your first call.",
        "posted_at": "2026-07-16",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-teleperformance-contact-centre",
    },
    {
        "id": "sa-039",
        "title": "Junior Financial Accountant",
        "company": "Absa",
        "location": "Johannesburg, Gauteng",
        "salary": "R23,000 - R29,000 / month",
        "description": "Support monthly reconciliations and reporting for a business unit under a senior accountant. A BCom (completed or final year) or SAIPA/SAICA articles progress required.",
        "posted_at": "2026-07-14",
        "email": "graduate.careers@absa.example",
        "url": "https://www.careerjet.co.za/jobad/example-absa-junior-accountant",
    },
    {
        "id": "sa-040",
        "title": "Warehouse Picker/Packer",
        "company": "Amazon South Africa",
        "location": "Cape Town, Western Cape",
        "salary": "R7,400 / month",
        "description": "Order picking and packing in a fast-paced fulfilment centre using handheld scanners. No experience required, full training given, shift work including weekends.",
        "posted_at": "2026-07-17",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-amazon-warehouse-picker",
    },
    {
        "id": "sa-041",
        "title": "Junior Web Designer",
        "company": "Webafrica",
        "location": "Cape Town, Western Cape (Remote)",
        "salary": "R16,000 - R21,000 / month",
        "description": "Build and maintain landing pages and email templates for an internet service provider. Figma and basic HTML/CSS -- a live portfolio link matters far more than a formal qualification.",
        "posted_at": "2026-07-15",
        "email": "",
        "url": "https://www.careerjet.co.za/jobad/example-webafrica-junior-web-designer",
    },
    {
        "id": "sa-042",
        "title": "Community Development Worker",
        "company": "SOS Children's Villages South Africa",
        "location": "Mthatha, Eastern Cape",
        "salary": "R7,200 / month",
        "description": "Support family strengthening and youth programmes in local communities. Social work/community development-related qualification or genuine, demonstrable volunteer experience required.",
        "posted_at": "2026-07-11",
        "email": "careers@sosvillages.example",
        "url": "https://www.careerjet.co.za/jobad/example-sos-community-development",
    },
]


def get_jobs(exclude_ids=None):
    """All available listings, minus any the caller already knows about
    (hidden or already applied to). Real pagination/search params would
    hang off this same function once it's backed by Careerjet."""
    exclude_ids = exclude_ids or set()
    return [j for j in MOCK_JOBS if j["id"] not in exclude_ids]


def get_job_by_id(job_id):
    return next((j for j in MOCK_JOBS if j["id"] == job_id), None)
